exports.productList = [
    {
        name: 'Bone',
        description: 'Um boné para proteger do sol!',
        tag : 'bone',
        price: 10,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/bone.png',
    },

    {
        name: 'Caderno',
        description: 'Um caderno para escrever historias que um dia irá contar',
        tag : 'caderno',
        price: 8,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/caderno.png',
    },

    {
        name: 'Tshirt',
        description: 'Uma tshirt para o verão',
        tag : 'tshirt',
        price: 15,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/tshirt.png',
    },

    {
        name: 'Camisola',
        description: 'Uma camisola para dias mais frios',
        tag : 'camisola',
        price: 20,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/camisola.png',
    },
    {
        name: 'Caneca',
        description: 'Uma caneca para a sua bebida favorita',
        tag : 'caneca',
        price: 6,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/caneca.png',
    },
    {
        name: 'Caneta',
        description: 'Uma caneta para por a escrita em dia',
        tag : 'caneta',
        price: 4,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/caneta.png',
    },
    {
        name: 'Chavena',
        description: 'Uma chávena para o seu café',
        tag : 'chavena',
        price: 5,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/chavena.png',
    },
    {
        name: 'Colunas Bluetooth',
        description: 'Colunas para ouvir boa musica',
        tag : 'colunasbluetooth',
        price: 22,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/colunasbluetooth.png',
    },
    {
        name: 'Garrafa Inox',
        description: 'Uma garrafa para os seus treinos',
        tag : 'garrafainox',
        price: 7,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/garrafainox.png',
    },
    {
        name: 'Urso',
        description: 'Um porta-chavés',
        tag : 'urso',
        price: 5,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/urso.png',
    },
    {
        name: 'Mochila',
        description: 'Uma mochila para os seus treinos',
        tag : 'mochila',
        price: 12,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/mochila.png',
    },
    {
        name: 'Saco',
        description: 'Um saco para o dia a dia',
        tag : 'saco',
        price: 6,
        inCart: 0,
        image: 'https://imagesual.fra1.digitaloceanspaces.com/saco.png',
    },

]